apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "store-chart.fullname" . }}-mysql
  labels:
    {{- include "store-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ include "store-chart.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "store-chart.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "store-chart.mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "store-chart.fullname" . }}-mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "store-chart.fullname" . }}-mysql-secret
              key: mysql-password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: {{ include "store-chart.fullname" . }}-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-chart.fullname" . }}-mysql
  labels:
    {{- include "store-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    {{- include "store-chart.mysql.selectorLabels" . | nindent 4 }}
  clusterIP: None
