apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "store-chart.fullname" . }}-mysql-pvc
  labels:
    {{- include "store-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mysql.storage.storageClass }}
  storageClassName: {{ .Values.mysql.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
